### PR TITLE
Episode 24 - Stephan Druskat

### PR DESCRIPTION
**Pull request by pweschmidt**
Hi Vanessa
this includes the png and the md file for episode 24 with Stephan Druskat
It also seems to include the md for the previous episode...

Best wishes
Peter

### CODE REVIEW

**Comment by vsoch** [comment]
hey @pweschmidt ! I think we chat a little about this for the last episode - if you are doing this always off of your master branch since we squash and merge the commits that you originally made will still be there (the previous episode!). Please start with a fresh fork and clone of the repository, then check out a branch for your episodes, and PR that branch to master here. We should only see commits for the current episode. Thanks!

**Comment by pweschmidt** [comment]
Yes we did, and sorry for the confusion again. I did actually create a branch for the episode but stupidly forgot to create a pull request from there. Will do that now.

pull request for the MP3 file should be ok though...

**Comment by vsoch** [comment]
Thank you!

**Comment by pweschmidt** [comment]
Closing this pull request as I created a new one with just the 2 added files in it

**Pull request closed without merging**
