### PR TITLE
Transcript for "Coding center in a box" with Adam Erck

### PR DESCRIPTION
**Pull request by ItsNotYou**
See #5 for details. As I'm not a native English speaker, I had some trouble understanding the following passages:

00:01:08 That's the sort of '''feeling one to bring to''' the computer science side of things.
00:03:25 A majority of our students coming through '''here at Bell''' are going through these liberal arts general education programs, [...]
00:09:14 I started using '''the Gaussian''' research software.
00:09:19 I started working with '''that genuine''' at University South Dakota.
00:14:09 '''I had about find that game thanks to Amazon'''.
00:14:22 I use my skills to '''post''' Minecraft servers at home.
00:14:57 Even if you don't use it immediately when you start your career it could be the difference between you getting promoted later on when your boss is like '''"let's grab a new position"''' you could be like [...]

All of these text pieces are marked with '''text piece''' in the committed markdown file.

### CODE REVIEW

**Comment by ItsNotYou** [comment]
Things that should be improved:
- [ ] Formatting. I don't know whether I can use the usual markdown formatting or not, but even simple options like bold type or italics would help.
- [ ] Paragraphs. Again, I don't know how the markdown gets translated. Paragraphs would definitely enhance the flow and I will gladly add them once I know how to.

**Comment by vsoch** [comment]
hey @ItsNotYou ! So don't worry about formatting - what I'll do is merge and then figure out how to format and integrate.

Let me listen to those passages and see if I can translate for you! It takes about 8-16 hours to edit a single episode, so I can assure you I've heard the words a lot of times (and have good chance to translate).

**Comment by vsoch** [comment]
- 00:01:08 That's the sort of '''feeling one to bring to''' the computer science side of things.

> "That's the sort of feeling that we wanted to bring to the computer science side of things"

Your translation is correct! He's saying that a writing center has a very personal, comfortable feeling, and he and his staff wanted to make their computer center in a box the same.


00:03:25 A majority of our students coming through '''here at Bell''' are going through these liberal arts general education programs, [...]

> A majority of our students coming throuhg here they all are going through these liberal arts general education programs

You got that one correct too - when he says "they all are" he stumbles on the words a bit, so it probably threw you off.


0:09:14 I started using '''the Gaussian''' research software.

> I started using the "Gaussian" research software

This is correct as well! He's referring to [this software](https://en.wikipedia.org/wiki/Gaussian_(software)) for chemistry.

00:09:19 I started working with '''that genuine''' at University South Dakota.

> I started working with Doug Jennewein at the University of South Dakota

00:14:09 '''I had about find that game thanks to Amazon'''.

> I happened to find it again thanks to Amazon

I think here he actually says "I happened on to find it again thanks to Amazon" so you can choose whichever one you think you hear. The first would be logical even if it's not perfect.

00:14:22 I use my skills to '''post''' Minecraft servers at home.

> I use my skills to host Minecraft servers at home.

00:14:57 Even if you don't use it immediately when you start your career it could be the difference between you getting promoted later on when your boss is like '''"let's grab a new position"''' you could be like [...]

> Even if you don't use it immediately when you start your career, It could be the difference between you getting promoted later on. when you're boss is like "Oh we've got a new position" you can be like "Oh, well you know I've got these computer skills. I could administrate, I can be a manager. And that could be the tipping point, that could make a difference for getting that promotion later on in your career."

**Comment by vsoch** [comment]
Perfect! If it's okay with you, I'll pull your branch, and work on it locally to figure out how to integrate into the site. I'll open another PR (including your commits) to add the final to master. Does that work for you?

**Comment by vsoch** [comment]
okay I got it working (and it looks good!) 

image

opening a PR in a minute!

**Comment by vsoch** [comment]
okay we're good to go! Please review https://github.com/USRSE/rse-stories/pull/7 and when it looks good, we will merge into master to make live on the site. Specifically, given a transcript is defined in the front-end matter for a post, it will link under the episode:

image

**Pull request merged**
